config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :links do
    member do
      put :upvote
      put :downvote
    end

    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy] do
    resources :comments, only: [:create, :destroy]

    member do
      put :upvote
      put :downvote
      get :insert_reply_form
      get :remove_reply_form
    end
  end

  root to: 'links#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_votable

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  after_create :increment_count
  after_destroy :decrement_count

  private

    def increment_count
      parent = commentable

      # Keep looping until we get to the parent which isn't a Comment model
      while parent.is_a? Comment
        parent = parent.commentable
      end

      parent.increment! :comments_count
    end

    def decrement_count
      parent = commentable

      # Keep looping until we get to the parent which isn't a Comment model
      while parent.is_a? Comment
        parent = parent.commentable
      end

      parent.decrement! :comments_count
    end
end

app/models/link.rb
class Link < ApplicationRecord
  acts_as_votable

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include Votable

  before_action :set_comment, only: [:insert_reply_form, :remove_reply_form]
  before_action :set_my_comment, only: [:destroy]
  before_action :set_commentable, only: [:create]
  before_action :authorized_user, only: [:destroy]

  # POST /comments
  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:success] = 'Comment was successfully created.'
      redirect_back fallback_location: root_path
    else
      flash[:error] = @comment.errors.full_messages.to_sentence
      redirect_back fallback_location: root_path
    end
  end

  def insert_reply_form
  end

  def remove_reply_form
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    flash[:success] = 'Comment was successfully destroyed.'
    redirect_back fallback_location: root_url
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_my_comment
      @comment = current_user.comments.find_by(id: params[:id])
    end

    def set_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Link.find_by_id(params[:link_id]) if params[:link_id]
    end

    def authorized_user
      if @comment.nil?
        flash[:error] = "Sorry, you can't edit someone else's comments."
        redirect_back fallback_location: root_path
      end
    end

    def comment_params
      params.require(:comment).permit(:user_id, :link_id, :content)
    end
end

app/controllers/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern

  def upvote
    votable_record.upvote_by current_user
    flash[:success] = 'Link was successfully upvoted.'
    redirect_back fallback_location: root_url
  end

  def downvote
    votable_record.downvote_from current_user
    flash[:success] = 'Link was successfully downvoted.'
    redirect_back fallback_location: root_url
  end

  private

    def votable_record
      @votable_record ||= controller_name.classify.constantize.find(params[:id])
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include Votable

  before_action :set_link, except: [:index, :new]
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :authorized_user, only: [:edit, :update, :destroy]

  # GET /links
  def index
    @links = Link.all.order(cached_weighted_average: :desc)
  end

  # GET /links/1
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  def create
    @link = current_user.links.build(link_params)

    if @link.save
      flash[:success] = 'Link was successfully created.'
      redirect_to @link
    else
      render :new
    end
  end

  # PATCH/PUT /links/1
  def update
    if @link.update(link_params)
      flash[:success] = 'Link was successfully updated.'
      redirect_to @link
    else
      render :edit
    end
  end

  # DELETE /links/1
  def destroy
    @link.destroy
    flash[:success] = 'Link was successfully destroyed.'
    redirect_to links_url
  end

  private

    def set_link
      @link = Link.find(params[:id])
    end

    def authorized_user
      @link = current_user.links.find_by(id: params[:id])

      if @link.nil?
        flash[:error] = "Sorry, you can't edit someone else's links."
        redirect_to links_path
      end
    end

    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then 'alert alert-info'
      when 'success' then 'alert alert-success'
      when 'error' then 'alert alert-danger'
      when 'alert' then 'alert alert-danger'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_actions.html.erb
<small class="text-muted">
  <% if user_signed_in? %>
    <%= link_to 'Reply', insert_reply_form_comment_path(comment),
          remote: 'true',
          class: 'text-muted' %>
    <% if comment.user == current_user -%>
      | <%= link_to 'Destroy', comment,
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: 'text-danger' %>
    <% end %>
  <% else %>
    <em>Sign in to reply</em>
  <% end %>
</small>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>" class="mb-1">
  <div class="d-flex flex-row">
    <div class="d-flex flex-column align-items-center mr-2">
      <%= render partial: 'shared/votes', locals: {
            record: comment,
            upvote_path: upvote_comment_path(comment),
            downvote_path: downvote_comment_path(comment) } %>
      <i class="threadline"></i>
    </div>

    <div class="flex-fill">
      <div class="text-muted">
        <small>
          Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.email %>
        </small>
      </div>

      <div class="lead">
        <%= comment.content %>
      </div>

      <div class="actions">
        <%= render partial: 'comments/actions', locals: { comment: comment } %>
      </div>

      <ul class="mt-2">
        <%= render partial: 'comments/comment',
              collection: comment.comments.order(cached_weighted_average: :desc) %>
      </ul>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [link, comment] do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>

app/views/comments/_reply.html.erb
<div class="mb-1">
  <small>
    <% if user_signed_in? %>
      <%= link_to 'Reply', remove_reply_form_comment_path(comment),
            remote: 'true',
            class: 'text-muted' %>
      <% if comment.user == current_user -%>
        | <%= link_to 'Destroy', comment,
                method: :delete,
                data: { confirm: 'Are you sure?' },
                class: 'text-danger' %>
      <% end %>
    <% end %>
  </small>
</div>

<div>
  <%= form_for [comment, Comment.new] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: 'Add a Reply',
            class: 'form-control' %>
    </div>

    <%= f.submit 'Reply', class: 'btn btn-sm btn-primary'  %>
    <%= link_to 'Cancel', remove_reply_form_comment_path(comment),
          remote: 'true',
          class: 'btn btn-sm btn-danger' %>
  <% end %>
</div>

app/views/comments/insert_reply_form.js.erb
$("#<%= dom_id(@comment) %> .actions").
  first().
  html("<%= j render partial: 'comments/reply', locals: { comment: @comment } %>")

app/views/comments/remove_reply_form.js.erb
$("#<%= dom_id(@comment) %> .actions").
  first().
  html("<%= j render partial: 'comments/actions', locals: { comment: @comment } %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seennit | A Reddit clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <%= link_to 'Seennit', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-link">
              <%= link_to 'Submit link', new_link_path, class: 'nav-link' %>
            </li>
            <li class="nav-link">
              <%= link_to 'Account', edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-link">
              <%= link_to 'Sign out', destroy_user_session_path, class: 'nav-link', method: :delete %>
            </li>
          <% else %>
            <li class="nav-link">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-link">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      <% flash.each do |level, msg| %>
        <%= content_tag(:div, msg, class: "#{flash_class(level)}") %>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for link do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id(link) %>" class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-2 col-md-1 d-flex flex-column align-items-center">
        <%= render partial: 'shared/votes', locals: {
              record: link,
              upvote_path: upvote_link_path(link),
              downvote_path: downvote_link_path(link) } %>
      </div>

      <div class="col-10 col-md-11">
        <div class="text-muted">
          <small>
            Submitted <strong><%= time_ago_in_words(link.created_at) %> ago</strong> by <%= link.user.email %>
            <% if link.user == current_user -%>
              | <%= link_to 'Destroy', link,
                    method: :delete,
                    data: { confirm: 'Are you sure?' },
                    class: "text-danger" %>
            <% end %>
          </small>
        </div>

        <div class="lead">
          <strong><%= link_to link.title, link.url %></strong>
        </div>

        <div class="mb-1">
          <small><%= link_to pluralize(link.comments_count, 'Comment'), link %></small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Links</h1>

<% if user_signed_in? %>
  <div class="row">
    <div class="col-12 mb-2">
      <%= link_to 'New Link', new_link_path %>
    </div>
  </div>
<% end %>


<div class="row">
  <% @links.each do |link| %>
    <div class="col-12">
      <%= render link %>
    </div>
  <% end %>
</div>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<div class="card mb-2">
  <div class="card-body">
    <div class="d-flex flex-row">
      <div class="d-flex flex-column align-items-center mr-4">
        <%= render partial: 'shared/votes', locals: {
              record: @link,
              upvote_path: upvote_link_path(@link),
              downvote_path: downvote_link_path(@link) } %>
      </div>

      <div>
        <h1>
          <strong><%= link_to @link.title, @link.url %></strong>
        </h1>

        <div class="comment-count">
          <small>
            <%= pluralize(@link.comments_count, 'Comment') %>
          </small>
        </div>

        <div class="link-actions">
          <% if @link.user == current_user %>
          <%= link_to 'Edit', edit_link_path(@link) %> |
          <%= link_to 'Destroy', @link,
          method: :delete,
          data: { confirm: 'Are you sure?' },
          class: 'text-danger' %> |
          <% end %>
          <%= link_to 'Back', links_path %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <div class="link-comment-form mb-4">
      <%= render partial: 'comments/form', locals: {
              link: @link,
              comment: Comment.new
            } %>
    </div>

    <div class="comments">
      <%= render partial: @link.comments.order(cached_weighted_average: :desc) %>
    </div>
  </div>
</div>

app/views/shared/_votes.html.erb
<% upvoted = current_user&.voted_up_for? record %>
<% downvoted = current_user&.voted_down_for? record %>

<%= link_to upvote_path, method: :put, class: "#{upvoted ? 'text-success' : 'text-muted'}" do %>
  <i class="fas fa-arrow-alt-circle-up"></i>
<% end %>

<%= record.weighted_score %>

<%= link_to downvote_path, method: :put, class: "#{downvoted ? 'text-danger' : 'text-muted'}" do %>
  <i class="fas fa-arrow-alt-circle-down"></i>
<% end %>